### ISSUE TITLE
Service Fabric needs to be upgraded again

### ISSUE THREAD

**Issue by jackbond** [microsoft/azure-pipelines-image-generation#1015]
**Describe the bug**
Can't build service fabric apps which target latest SF SDK.

**Expected behavior**
Can build service fabric apps which target latest SF SDK.

**Actual behavior**
Can't build service fabric apps which target latest SF SDK.

1.) Attempt to build service fabric app which targets latest SF SDK

**Image impacted**
Hosted Windows 2019 with VS2019 image

**Comment by jstevans** [comment]
Ping -- @sachinma / @bishal-pdMSFT, are you still the right contacts to perform this upgrade, per the comment by @RoopeshNair in #213?

We need 6.5 CU 2 or later (preferably the latest, [which is currently 6.5CU5][sf-6-5-cu5]) in order to [make use of MITS][mits].

[sf-6-5-cu5];https://github.com/Azure/service-fabric/blob/master/release_notes/Service_Fabric_ReleaseNotes_65CU5.md
[mits]:https://docs.microsoft.com/en-us/azure/service-fabric/how-to-deploy-service-fabric-application-system-assigned-managed-identity

**Comment by vinodkumar3** [comment]
We've figured out the issue, we're now working with Azure Pipeline: Hosted Agents team for the fix.
Thanks for raising this issue.

**Comment by vinodkumar3** [comment]
Issue has been fixed and will be available in upcoming release.
