### ISSUE TITLE
Hosted Ubuntu 1604 Terraform version incorrect

### ISSUE THREAD

**Issue by Lokiem** [microsoft/azure-pipelines-image-generation#1027]
As of checking today, Terraform is on v0.12.1 on the hosted ubuntu 1604 agent.

Is there anywhere kept more up to date on versions, or somewhere that informs people when breaking changes are introduced other than the readme here?

**Comment by ArieHein** [comment]
make sure you have a task at the start to force 0.11.x. I always have steps like that to shield yourself from unannounced issues as this one broke some of our builds where devs didnt follow original instructions. Also a good way to make sure you have required_version in your terraform block

**Comment by bondido** [comment]
@ArieHein how can we force agent to use specific terraform version?

**Comment by ArieHein** [comment]
@bondido use the version command

https://marketplace.visualstudio.com/items?itemName=charleszipp.azure-pipelines-tasks-terraform

**Comment by shashankbarsin** [comment]
@Lokiem the Terraform installer script picks up the latest stable version available for Terraform at the time of each image generation. Closing out this issue as the right version of Terraform is installed with each release of the image.

For all tools installed on the images, the release notes for the repo contain information on the versions of these tools. It is possible be notified only for releases of this repository by [watching the repository in 'Releases only' mode](https://help.github.com/en/articles/watching-and-unwatching-releases-for-a-repository)

If terraform init is failing due to incompatibility between terraform version and the provider version, would [declaring providers using version constraint string instead of a single explicit version](https://www.terraform.io/docs/configuration/providers.html#version-provider-versions) help?
