### ISSUE TITLE
Inno Setup 6 is now installed instead of Inno Setup 5 on Windows images.

### ISSUE THREAD

**Issue by nelsonjchen** [microsoft/azure-pipelines-image-generation#1072]
The documentation hasn't been updated though. It still says Inno Setup 5.

Also, major version bumps like this are a bit disturbing. The `choco install` is pretty unpinned. Is this the norm? 

Related: https://github.com/debauchee/barrier/issues/354

**Comment by kaylangan** [comment]
@shadyysf I see we updated the README for the M154 release in #1040. Do you know if the Inno version is correct? I see VS2019 is reporting Inno Setup 6.

@nelsonjchen For some tools we always pull latest--Inno is one of them. If you need a specific version, we'd recommend you do a check in your build scripts and optionally install the specific version if it's not found.

**Comment by shadyysf** [comment]
@kaylangan and @nelsonjchen, the source of truth for the documentation is the Agent pools "Details" tab which is accessible through your project setting in AzureDevOps. We also update the documentation on the release branch where a certain VM image has been built. In this case, you can find the updated docs in "releases/VS2017/154" and "releases/VS2019/154" branches for the VS2017 and the VS2019 images respectively. We're thinking of removing those readme files from the master branch altogether due to the confusion they create.

@alepauly for FYI.
