### ISSUE TITLE
Why no macOS custom images?

### ISSUE THREAD

**Issue by lucasyvas** [microsoft/azure-pipelines-image-generation#1118]
Is the lack of support for it a technical or legal limitation?

**Comment by thejoebourneidentity** [comment]
Hi @lucasyvas, we don't currently support custom images mostly due to cost and scale. Eventually our goal is to support elastically scaling pools of private agents. This will allow you to point Azure Pipelines to your infrastructure (local or on prem) and use your own custom images: https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/byos.md

**Comment by lucasyvas** [comment]
Thanks for the quick reply!
