### ISSUE TITLE
Unable to build the image withing 6 hours

### ISSUE THREAD

**Issue by nreddipalle** [microsoft/azure-pipelines-image-generation#1123]
**Describe the bug**
I am unable to build VS 2017 windows image file within 6 hours.. I am using Microsoft hosted agent running packer image generation on Standard_DS5_v2 SKU. Please recommend a best way to successfully build an image.

**Expected behavior**
Successful generation of VS2017 image

**Actual behavior**
Agent timing out after 6 hours..The agent has received a shutdown signal. This can happen when the agent service is stopped, or a manually started agent is canceled."

1. Step 1
2. Step 2

**Image impacted**
Add a label for each image that has the bug (e.g., ubuntu, mac, window)

**Comment by alepauly** [comment]
@nreddipalle Unfortunately, due to how long it takes to build the VS2017, it cannot be build using a hosted agent (since they in fact allow builds of at most 6 hours). If building the image as part of a Pipeline you can always instantiate your own machine (physical or virtual) and register it as an agent for your Azure DevOps project. This type of s[elf-hosted agent](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#install) doesn't have the 6 hour limitation.
