### ISSUE TITLE
Add Ruby to the cached Docker Images

### ISSUE THREAD

**Issue by jebw** [microsoft/azure-pipelines-image-generation#1160]
**Tool information**
- Tool name: Ruby
- Add or update? Add to cached Docker Images
- Desired version: 2.5 and 2.6
- If this is an add request:
  - Brief description of tool: Popular programming language used by Ruby on Rails
  - URL for tool's homepage: https://www.ruby-lang.org/en/

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [x] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [x] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Add the appropriate label for the image or images that should be updated (e.g., macOS 10.13, macOS 10.14, ubuntu, VS2017, VS2019, WINCON).

ubuntu

**Workaround**

download the ruby image as part of the build process

**Are you willing to submit a PR?**

https://github.com/microsoft/azure-pipelines-image-generation/pull/1159

**Comment by kaylangan** [comment]
@jebw this may be a naive question. What benefit does caching these containers have over using the [Use Ruby Version](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-ruby-version?view=azure-devops) task?

**Comment by shashankbarsin** [comment]
@kaylangan Docker builds which use ruby based images as base image (for example ruby:alpine) will be faster.

@jebw the list of currently cached images on the hosted agents are based on the languages or tools most commonly used by our customers in build pipelines. While we do have a good support for Ruby currently in the form of ruby binaries on Ubuntu/Windows agents, the number of pipelines doing Ruby based builds is very small in comparison to the number of pipelines using the currently cached tools and languages.

As the image will consume storage space on the agents. the smallest variant - ruby:alpine tag, is 51 MB in size. Caching images for every language's alpine tag such as python:alpine, ruby:alpine will consume lot of disk space. So we may not add it to the list in the near future.

While I'll close out this issue for now, we are however investigating options on reutilizing cached images from colocated container registries instead of caching them on the agent itself. We don't have a firm timeline on that yet. But I will add a comment on this thread with a link to our release notes when we do release this feature in the future.
