### ISSUE TITLE
Update/Add Chrome 76

### ISSUE THREAD

**Issue by dannythomas13** [microsoft/azure-pipelines-image-generation#1186]
All of our dev and client machines have Chrome set to auto-update and are now on version 76 but I can see from the image that the hosted build agent is still on version 75. Can this please be updated?

Additionally to stop this from happening every few weeks can someone tell me if within Selenium tests I can specify a fixed version of chrome to use so that the tests can remain stable even when the browser is updated?

**Comment by MatthewSteeples** [comment]
The only way to control the version of the browser is to host your own agents (or use some method of installing it on the hosted agent when it starts up). The main problem we've experienced from this is needing to use the correct version of the Selenium WebDriver, but you can get round this by detecting whether an environment variable is set and using the WebDriver that is pre-installed on the build server instead so that the versions (browser and WebDriver) are always in sync
