### ISSUE TITLE
Pre-install main iOS Simulators for all Xcode versions

### ISSUE THREAD

**Issue by maxim-lobanov** [microsoft/azure-pipelines-image-generation#1199]
**Tool information**
- Tool name: iOS Simulators

**Context**
For now only default iOS simulators are installed on macOS images. The list of pre-installed simulators is located in [macOS High Sierra docs](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.13-Readme.md#installed-simulators) and [macOS Mojave docs](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.13-Readme.md#installed-simulators).

Sometimes customers need to use non-default simulators (like iOS 11 simulators for Xcode 10.3). For now they have to use `xcversion` tool to install those simulators during the build. It takes some time and it would be great to pre-install some simulators for all Xcode versions.

**Suggestion**
Pre-install the latest minor version of each major version of Xcode (like 10.3.2, 11.4).
This issue was created to track customers' interest for this feature.

**Areas and ecosystems**

- [x] iOS, macOS, and Apple-specific tools

**Image impacted**
macOS 10.13, macOS 10.14

**Workaround**
The command `xcversion simulators --install='iOS <VERSION>'` can be used to install specific simulator for all Xcode versions.

**Comment by max-lobanov** [comment]
@nilofer, I have created separate issue to track customers' requests for this feature

**Comment by Jon889** [comment]
Is there much usage of old versions of Xcode? It doesn't really make sense that the most simulators are installed for the oldest version of Xcode. it really should be the other way round then if you have a need to use more simulators on the old versions of Xcode you can use the diversion workaround.

**Comment by Jon889** [comment]
Our pipelines have all just started failing as the 12.2 simulators were removed. This is fair enough because it's not the latest minor version. But this setup still doesn't make sense (on other CI platforms this I'm pretty sure this isn't an issue at all).

The logical thing to do would be have the latest minor version of the old major versions. And then for the latest major version have all the minor version runtimes. This would allow it to be stable, and save space.

**Comment by max-lobanov** [comment]
@Jon889 , Thank you for your point and your context. That definitely makes sense and we should consider it.

As for the 12.2 simulators, they are still on image and were not removed.
The latest image update changed default Xcode version. Previously, it was Xcode 10.2.1, and recently it was updated to Xcode 10.3.
- Xcode 10.2.1 contains iOS 12.2 simulators by default
- Xcode 10.3 contains iOS 12.4 simulators by default
If you want to use iOS 12.2 simulators, you can specify Xcode 10.2.1 instead of default one.
If you have a case to use iOS 12.2 simulators with Xcode 10.3, you have to use `xcversion` tool.

**Comment by Jon889** [comment]
Yep sorry just realised that the Xcode version updated.

btw, does the image being deployed happen at specified times? (like at a certain time every week?)

**Comment by max-lobanov** [comment]
@Jon889 , We deploy image on weekly basis but day of week can be different.

The image deployment is quite a long process and usually we update docs as soon as deployment is fully completed and all machines are updated.

**Comment by diogot** [comment]
This would be great!

**Comment by Jon889** [comment]
Just run into this problem again. For some reason it's not possible to install iOS 12.4 simulators using xcversion https://github.com/xcpretty/xcode-install/issues/342 so we've had to switch to 12.2 which isn't ideal, but the problem seems to be from Apple so there's not much to be done about it, and it doesn't affect the following:

The real annoyance is that we want to switch to using Xcode 11 (so we can build against the iOS 13 SDK and use Swift 5.1), but most of our customers are still on iOS 12 so we want to keep testing on iOS 12 for our PRs. So we have to use xcversion to install the iOS 12 simulators (whether that's 12.2 or 12.4 is irrelevant). **This adds 6 minutes to our build time**. Which isn't ok for PR builds.

So even if you don't fulfil the original request can you please preinstall the last version of the previous iOS when a new major iOS/Xcode version comes out? At least until the majority of customers are on the new iOS version?

I'm only asking for one simulator to be installed now, I can cope with not having older versions of iOS preinstalled :)

**Comment by Jon889** [comment]
Hitting this problem again...

On Xcode 11, if I run `xcrun simctl list` I get this output for the installed runtimes:

```
iOS 8.4 (8.4 - 12H141) - com.apple.CoreSimulator.SimRuntime.iOS-8-4 
iOS 9.0 (9.0 - 13A344) - com.apple.CoreSimulator.SimRuntime.iOS-9-0 
iOS 9.1 (9.1 - 13B143) - com.apple.CoreSimulator.SimRuntime.iOS-9-1 
iOS 9.2 (9.2 - 13C75) - com.apple.CoreSimulator.SimRuntime.iOS-9-2 
iOS 9.3 (9.3 - 13E233) - com.apple.CoreSimulator.SimRuntime.iOS-9-3 
iOS 10.0 (10.0 - 14A345) - com.apple.CoreSimulator.SimRuntime.iOS-10-0 
iOS 10.1 (10.1 - 14B72) - com.apple.CoreSimulator.SimRuntime.iOS-10-1 
iOS 10.2 (10.2 - 14C89) - com.apple.CoreSimulator.SimRuntime.iOS-10-2 
iOS 13.0 (13.0 - 17A577a) - com.apple.CoreSimulator.SimRuntime.iOS-13-0 
tvOS 13.0 (13.0 - 17J577) - com.apple.CoreSimulator.SimRuntime.tvOS-13-0 
watchOS 6.0 (6.0 - 17R575) - com.apple.CoreSimulator.SimRuntime.watchOS-6-0 
```

Having iOS 8 is 100% not useful to anyone. and iOS 9 runtime is probably not useful to anyone.

The previous justification for not having more runtimes preinstalled is because of space. Can you please install a version of iOS 11 and 12 now? and remove two versions from the iOS 9 and 8 runtimes. That way there is no extra space taken up.

Build times have now had an extra 5-10 minutes added to them to because of having to install the simulators.

There really is no need for iOS 8 and 4 versions of iOS 9. But there is a need to have the later iOS versions... it's that simple...

**Comment by PatrickGaissert** [comment]
I agree with everyone in this thread. This is a major issue for us, since we need the iOS 12.4 Simulator in Xcode 11 for our UI tests to run correctly (seems to be an issue with the iOS 13 Simulator). Please always install the last minor versions of the last 2 major releases, as Apple recommends supporting them with your apps. This would mean iOS 11.4 and 12.4 in Xcode 11.

**Comment by Jon889** [comment]
Please can this change be made soon, definitely before WWDC this year. I don’t feel like wasting more of my and my teams time having to handle this situation again this year.

**Comment by Jon889** [comment]
@maxim-lobanov
Just got the mail about the macOS 10.13 image is being removed and Xcode versions older than 9.4.1 won’t be supported, can this change be made with the simulators?

**Comment by mellkord** [comment]
Same issue here. We are testing our applications on all major versions we support and not having iOS 11 and iOS 12 in the image is just insane. It just completely removes all the sense in using Azure Pipelines because instead of focusing on pipeline as a code or as a configuration we have to setup and maintain the environment. Yes, we have a workaround but this workaround adds 10 more minutes to all our build which is 2-3 TIMES compare to compilation time.  I would suggest to add ALL runtimes which are available to the image and not think about which version the majority of developers are using.

**Comment by maxim-lobanov** [comment]
Since this work item is pretty popular - moving it to the new repository to track activity: https://github.com/actions/virtual-environments/issues/551
