### ISSUE TITLE
xcode archive: physical platform is "Ineligible destination"

### ISSUE THREAD

**Issue by sbolotovms** [microsoft/azure-pipelines-image-generation#1221]
**Describe the bug**
For CI build we're trying to perform xcode archive on the project but it fails since archive requires target platform to be non-simulator.

**Expected behavior**
`xcode archive` successfully completes for generic iOS device.

**Actual behavior**
[log_25_24753660.zip](https://github.com/microsoft/azure-pipelines-image-generation/files/3585759/log_25_24753660.zip)

**Image impacted**
MacOS 10.14

**Error log**
```
Ineligible destinations for the "PhoneFactor" scheme:
	{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
	{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }
```

**Comment by max-lobanov** [comment]
Hi @sbolotovms, It looks like incorrect params are used for `Xcode` task.
I see that you have created the same issue in [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues/11288) repo and I think it is the better place for this issue.
I have already shared the possible fix in [azure-pipelines-tasks issue](https://github.com/microsoft/azure-pipelines-tasks/issues/11288).

I am going to close this issue since it is not image-specific.
