### ISSUE TITLE
Error : The value for PublishProfile is set to 'FileSystem', expected to find the file at 'xxx\Properties\PublishProfiles\FileSystem.pubxml'

### ISSUE THREAD

**Issue by lucavgobbi** [microsoft/azure-pipelines-image-generation#1276]
**Describe the bug**
As of September 27 the windows-2019 started throwing the following error (even when using the same code):
 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\Web\Microsoft.Web.Publishing.targets(4360,5): Error : The value for PublishProfile is set to 'FileSystem', expected to find the file at 'xxx\Properties\PublishProfiles\FileSystem.pubxml' but it could not be found."

YAML for build step:

steps:
- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: removed/forPrivacy.sln
    vsVersion: 16.0
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\" '
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    clean: true
    maximumCpuCount: true
    msbuildArchitecture: x64

- The same error occur on every Azure WebJobs SDK projects.
- The projects where the error happens are NET472 using the new csproj format. 
- There is another WebJobs SDK project using the old csproj format that doesn't throw an error.
- The solution also contains a NET472 WebApp, Windows Console and Azure Functions projects
- Adding a Publish profile to FileSystem seems to solve the issue
- Using MSBuild on my local machine with the exact same parameters works fine

**Expected behavior**
The build to complete successfully as it used to do until September 27

**Image impacted**
windows-2019

**Comment by Brilbroeder** [comment]
We experience the same problem and so far found no way to solve it or a work-around. I our case it is generated from the build pipelines on azure devops.

**Comment by philmacdonald2** [comment]
We are experiencing the same issue with old-csproj format webjobs as well, on .NET 4.6.1. So far, we have been unable to find a workaround.

**Comment by philmacdonald2** [comment]
Renaming or adding additional Publish Profiles with the name FileSystem.pubxml does seem to work, as stated by @lucavgobbi.

I can reproduce this issue with local MSBuild, so it's possible it's an MSBuild issue - MSBuild version 16.3.0.46305

**Comment by alitahir360** [comment]
We are having the exact same problem.  I had a successful build on Sept 24th and builds as of yesterday are failing due to this issue.  Will try the FileSystem.pubxml to temporarily fix the issue.

**Comment by NickMOrlando** [comment]
We are also seeing this failure as of yesterday (2019-09-30) on all Dev Ops pipelines.

The suggested workaround did work for us as well

**Comment by StingyJack** [comment]
We also just started experiencing this issue as well. The pipeline is complaining about two webjobs. I can run the same build definition against the last changeset that built correctly and this still produces the error described.

**Comment by anderslaub** [comment]
Same issue started occurring today on several solutions out of nowhere.

I've made a different work-around that fix the issue without modifying the codebase. 
 
Before the msbuild webpublish target is called remove the ValidatePublishProfileSettings target from the msbuild property WebPublishDependsOn

`  <PropertyGroup>  
<WebPublishDependsOn>$([System.String]::Copy('$(WebPublishDependsOn)').Replace('ValidatePublishProfileSettings', '').Replace(';','').Trim())</WebPublishDependsOn>  
</PropertyGroup>`

Make sure to set the property _after_ Microsoft.WebApplication.targets is imported or it will be overridden.

**Comment by azureDaveOps** [comment]
Thanks for bringing this to our attention.  We are working on a fix.

**Comment by wireznak** [comment]
This issue is still under investigation, but we've gotten a good idea of the root cause and have forwarded the description and the apparent cause to the responsible parties.

**Comment by StingyJack** [comment]
@wireznak - kindly point our pitchforks in their direction.

J/K - thanks for the update.

**Comment by vijayrkn** [comment]
> * The same error occur on every Azure WebJobs SDK projects.
> * The projects where the error happens are NET472 using the new csproj format.
> * There is another WebJobs SDK project using the old csproj format that doesn't throw an error.

Can someone please share a sample WebJobs SDK project (using the new csproj format) that fails in Azure DevOps? I am mostly interested in the Package reference.

**Comment by StingyJack** [comment]
> Can someone please share a sample WebJobs SDK project (using the new csproj format) that fails in Azure DevOps? I am mostly interested in the Package reference

@vijayrkn - not from me. Because I don't want this to be fixed for only the one (worst) proj file and nuget format combination and then coerced into updating all our projects to fix some dumb bug in DevOps.

Whatever was changed a few weeks ago regarding these components should just be reverted. It should not be that difficult for an organization like MSFT.

It's what I would be required to do by my customers after I didn't have an immediate fix.

**Comment by vijayrkn** [comment]
@StingyJack - I am just trying to find the root cause of the issue and the project file that fails would really help with the investigation.

**Comment by lucavgobbi** [comment]
@vijayrkn this is all I'm able to share:

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.2.0" />
    <PackageReference Include="Microsoft.AspNet.Identity.EntityFramework" Version="2.2.2" />
    <PackageReference Include="Microsoft.Azure.KeyVault" Version="2.3.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="2.3.0" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="5.2.1" />
    <PackageReference Include="Microsoft.SqlServer.Management.AlwaysEncrypted.AzureKeyVaultProvider" Version="2.1.0" />
    <PackageReference Include="Microsoft.Web.WebJobs.Publish" Version="2.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
    <PackageReference Include="System.Spatial" Version="5.8.4" />
    <PackageReference Include="Microsoft.Data.Edm" Version="5.8.4" />
    <PackageReference Include="Microsoft.Data.OData" Version="5.8.4" />
    <PackageReference Include="Microsoft.Data.Services.Client" Version="5.8.4" />
    <PackageReference Include="Microsoft.WindowsAzure.ConfigurationManager" Version="3.2.3" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Core" Version="2.3.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="2.3.0" />
    <PackageReference Include="Microsoft.Azure.KeyVault.Core" Version="2.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..xxx.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>
</Project>`

**Comment by vijayrkn** [comment]
@lucavgobbi - Thank you for sharing this. 

Can you try removing this package reference from this project file? This package contains targets that are only meant for non-sdk style projects. 

`    <PackageReference Include="Microsoft.Web.WebJobs.Publish" Version="2.0.0" />`

Do you know how this package got added to this Sdk style project?

**Comment by StingyJack** [comment]
@vijayrkn - did you attempt the repro steps given? Netfx, webjob.

The other packages are for webjob 2.x, which is also all the webjobs we have. 3.x depends on  crummy designs and design choices and it is a bunch of work to convert for negative benefits.

**Comment by lucavgobbi** [comment]
@vijayrkn I believe I've updated those packages using Nuget Package Manager interface on VS2019 to match the version of other webjobs I have.

I've created a new Webjob on VS2019 and NET472, this is the csproj created by the template:

`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="11.0.1"/>
    <PackageReference Include="System.Spatial" Version="5.8.3"/>
    <PackageReference Include="Microsoft.Data.Edm" Version="5.8.3"/>
    <PackageReference Include="Microsoft.Data.OData" Version="5.8.3"/>
    <PackageReference Include="Microsoft.Data.Services.Client" Version="5.8.3"/>
    <PackageReference Include="Microsoft.WindowsAzure.ConfigurationManager" Version="3.2.1"/>
    <PackageReference Include="WindowsAzure.Storage" Version="7.0.0"/>
    <PackageReference Include="Microsoft.Azure.WebJobs.Core" Version="1.1.2"/>    
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="1.1.2"/>
    <PackageReference Include="Microsoft.Azure.KeyVault.Core" Version="1.0.0"/>
  </ItemGroup>
</Project>
`

As @StingyJack commented, I've tried to update to 3.x but there were a lot of breaking changes that I didn't have time to deal with.

**Comment by vijayrkn** [comment]
@StingyJack @lucabol - I was specifically talking about this one tooling package 'Microsoft.Web.WebJobs.Publish'. As you have shown here [csproj.txt](https://github.com/microsoft/azure-pipelines-image-generation/files/3712527/csproj.txt), this is not part of the SDK project template. 

`<PackageReference Include="Microsoft.Web.WebJobs.Publish" Version="2.0.0" />`

I was not suggesting to upgrade the WebJobs from Net472 to 3.x. Sorry if I wasn't clear. 

This specific tools package 'Microsoft.Web.WebJobs.Publish' has targets that will not work well with sdk style projects. All the required targets for sdk style projects come from the first line in your csproj (`<Project Sdk="Microsoft.NET.Sdk">`). It should be safe to remove this package reference since the sdk style projects does not need it. 

`<PackageReference Include="Microsoft.Web.WebJobs.Publish" Version="2.0.0" />`

**Comment by StingyJack** [comment]
@vijayrkn  - a build definition and a branch at a specific changeset built without issue about two or three weeks ago. The same build definition executed against the same changeset version fails today.

If the package was there before, it was there without this problem before. 

Something was changed in the build agents or processes that created this break. Whatever that was needs to be addressed, not our code.

**Comment by StingyJack** [comment]
Also, if this package has some incompatibility problem, that should be blocking the installation of the package.

**Comment by vijayrkn** [comment]
@StingyJack As I mentioned, I am just trying to get to the root of the problem here. Looking at the csproj, this is the only thing that looks like could cause the error as mentioned.  If this is in fact the issue, we will have to understand why it started failing not rather than before.

**Comment by StingyJack** [comment]
While you research, the latest changes should be getting reverted or toggled off.  Its not really acceptable in most IT circles to leave your customers productivity affected for 12+ days while you triage, route, and analyze an issue.  

Creating a proj and env to repro the condition you suspect sounds like something you should do asap rather than conjecturing.

I will point out that you still seem to be focusing on something that will require your customers to perform unexpected work. Had you been speaking about the the latest changes to your platform and how they could have broken existing code/builds, I would probably not be getting that impression.

**Comment by RossTheHammer** [comment]
@vijayrkn I tried your fix, removing the reference to Microsoft.Web.WebJobs.Publish, and while it permits the build to complete, the build does not contain the webjob artifacts, so it is not deployable. Obviously, that is not a viable solution.

**Comment by vijayrkn** [comment]
If you want to deploy the Sdk style WebJobs project, then you can update the first line to include Microsoft.NET.Sdk.Publish

`<Project Sdk="Microsoft.NET.Sdk;Microsoft.NET.Sdk.Publish">`

**Comment by lucavgobbi** [comment]
@vijayrkn I've tried your suggestion. I've removed Microsoft.Web.WebJobs.Publish and updated <Project Sdk="Microsoft.NET.Sdk;Microsoft.NET.Sdk.Publish">.

Got the following error during build:
##[error]xxx.csproj(0,0): Error MSB4057: The target "ResolveWebJobFiles" does not exist in the project.

**Comment by StingyJack** [comment]
@vijayrkn ... There you go trying to solve along one path. The wrong path.

That path doesn't make a bit of sense when it's *not our code that changed.*

I do not know you personally, and have had no other known interaction with you specifically, but if by some off-chance you are able to claim any success with this approach, past experience dictates that whatever sliver or shred of workaround can be found will be attempted to be canonized - with no regard to the ethics of the situation, or the work it will create for your customers. 

MSFT broke it, MSFT should bear the sole burden of researching and fixing it. Asking us for some assistance is ok. Asking us to try SWAG is unquestionably inappropriate.

**Comment by NickMOrlando** [comment]
@StringyJack sums this perfectly, although maybe a little more bluntly than I would have myself.

@vijaykrn-

The system worked prior to September 27.

The system stopped working on September 27.

What changes were made to the system on or around that date? Because none of our separate codebases were changed, and yet all of them are suffering from the same issue since September 27.

**Comment by vijayrkn** [comment]
@RossTheHammer @lucavgobbi @StingyJack @NickMOrlando - I am really sorry that you are running into this issue. I am from the Product team that maintains the target that you are seeing in the error message. The last update to this NuGet package in the error was done more than an year ago (https://www.nuget.org/packages/Microsoft.Web.WebJobs.Publish/2.0.0). So unfortunately there is nothing to rollback in the package. 

I am not fully aware of what changes were rolled out on September 27. @azureDaveOps - Until we figure out the cause for these failures, is there a way for our customers to opt into the old behavior? 

As far as the error goes - I have created a repo here with the same setup as the description above - https://github.com/vijayrkn/Repro1276 (This has a package command with similar args as mentioned above - https://github.com/vijayrkn/Repro1276/blob/master/Package.cmd). 

I will try to run this on Azure DevOps to see if I can reproduce the same issue.  If the project set up different to get to the error, please let me know. Appreciate your help with this.

**Comment by StingyJack** [comment]
@vijayrkn - I'm not talking about rolling back the package because thats still the wrong direction to be looking, but I think you are getting the point by asking @azureDaveOps that question, so I'll share some proj details below.   You guys should really have a changelog or release notes or something regarding what gets deployed at any time, but with the recent "streamlining" it doesnt surprise me if MSFT actually didn't, _(By "streamlining" I mean when you deleted our build histories without notice or warning when you changed the retention policy management. The deletion included version control build number labels so I cant hotfix production reliably. The frustrating runaround and stonewalling I'm getting on several week old support request to at least get the labels and changeset mappings restored so I'm not totally screwed if I need to make a hotfix is most of the reason for my "bluntness".   If you would like me to be less salty in conversation, please have your fellow MSFTers stop creating risk and confusion for lifelong customers where it wasn't before and does need not be.)_


The WebJobs472Sdk should only have `Microsoft.NET.Sdk` if that is what the webjob 2.0 project template creates. However I dont think thats related to the problem at all because the OP error happened in a build that had one webjob with just the `Microsoft.NET.Sdk` and one that had `Microsoft.NET.Sdk` and `Microsoft.NET.Sdk.Publish`

There are a few other things missing in it, like project references, source control bindings, other packages, and a few Reference Includes

Here is the rest of the project file (some private packages and project references removed)
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.60.6" />
    <PackageReference Include="EntityFramework" Version="6.2.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="2.3.0" />
    <PackageReference Include="Microsoft.Web.WebJobs.Publish" Version="2.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
    <PackageReference Include="System.Spatial" Version="5.8.3" />
    <PackageReference Include="Microsoft.Data.Edm" Version="5.8.3" />
    <PackageReference Include="Microsoft.Data.OData" Version="5.8.3" />
    <PackageReference Include="Microsoft.Data.Services.Client" Version="5.8.3" />
    <PackageReference Include="Microsoft.WindowsAzure.ConfigurationManager" Version="3.2.3" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Core" Version="2.3.0" />    
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="2.3.0" />
    <PackageReference Include="Microsoft.Azure.KeyVault.Core" Version="3.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Folder1\SomeOtherProjectInTheSolution.csproj" />
    <ProjectReference Include="..\Folder2\YetAnotherProjectInTheSolution.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
</Project>

```
The other project with the additional SDK publish directive/attribute also has these elements that the other doesn't. 
```
 <PropertyGroup>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>
```

I can also share the team project, tfvc changeset and build definition numbers that I mentioned that worked and then didn't, but it would have to be a private comment on the DevComm issue I linked to earlier.

**Comment by vijayrkn** [comment]
> There are a few other things missing in it, like project references, source control bindings, other packages, and a few Reference Includes

These should not impact the above issue. But I can add them. 

Just to get a repro, I will add this package
`    <PackageReference Include="Microsoft.Web.WebJobs.Publish" Version="2.0.0" />`

But I want to make it clear that this package is not supported for SDK style projects. 

@RossTheHammer 
>@vijayrkn I tried your fix, removing the reference to Microsoft.Web.WebJobs.Publish, and while it permits the build to complete, the build does not contain the webjob artifacts, so it is not deployable.

I just tried creating a pipeline with my sample repo and it seems to be working fine without the package (https://github.com/vijayrkn/Repro1276). May be there is something else that is missing?

**Comment by thecontrarycat** [comment]
> Just to get a repro, I will add this package
> ` <PackageReference Include="Microsoft.Web.WebJobs.Publish" Version="2.0.0" />`
> 
> But I want to make it clear that this package is not supported for SDK style projects.

Is an unrelated github issue tracker really the place to be making statements about package support?  If that package doesn't work with Sdk projects anymore (when it did on the 27th September) then the package needs to be updated by its author and a warning written to the build log.  You should also update the nuget.org page for your package warning people that it is deprecated and should be replaced with the Microsoft.NET.Sdk.Publish reference instead.

**Comment by vijayrkn** [comment]
> If that package doesn't work with Sdk projects anymore (when it did on the 27th September) then the package needs to be updated by its author and a warning written to the build log

We will get the package updated to state that it is unsupported for Sdk projects. Please note that this package is still supported & the recommended mechanism to package/publish non-sdk based WebJob projects.

**Comment by vijayrkn** [comment]
I was able to reproduce the issue with the latest .NET Core Sdk. The easiest work-around is to pass this additional property to the build task (without making any code changes)(https://github.com/vijayrkn/Repro1276/blob/1fd89e8534629d5a61501f833a004c78d8e9d959/azure-pipelines.yml#L28).

`/p:PublishProfileImported=true`

I have verified that this works in Azure DevOps.

**Comment by StingyJack** [comment]
> I was able to reproduce the issue with the latest .NET Core Sdk. 

@vijayrkn - Thanks but I'm not using that. Did you try with a net472 webjobs 2.0 project that a few of us reported? (I'm not really a fan of new framework bugs, feature loss, and hot garbage json config files. I will also usually manually revert new projects back to the older explicit format, but the affected webjobs were written by a coworker and )


> I do not know you personally, and have had no other known interaction with you specifically, but if by some off-chance you are able to claim any success with this approach, past experience dictates that whatever sliver or shred of workaround can be found will be attempted to be canonized - with no regard to the ethics of the situation, or the work it will create for your customers. -Me

> The *easiest* work-around is to pass this additional property to the build task (without making any code changes) - @vijayrkn 

No, not true. The easiest work-around for us is to do nothing and for you to fix the problem someone from your team created. This is not a statement of malice; as bugs happen to everyone. However it is a statement of growing frustration because you are falling into the pattern I prognosticated, despite being made aware of the pattern and why its detrimental.

Its also not true because I dont think we have any idea what that will do to the other projects in the solution that are getting built and packaged (published to artifacts) with the same vs or msbuild task.

Compared to the effort in finding the workaround you mentioned, how much effort was spent researching the changes that went into production and how to remediate or rollback those? 

Another workaround is to not use the Sdk style project file format and nuget package reference style, avoiding almost any new framework or format bugs like this (as well as allowing you to know what exactly is going into the program or module you are authoring.)

**Comment by vijayrkn** [comment]
I am trying to help here as much as I can. 

>Did you try with a net472 webjobs 2.0 project that a few of us reported
- All the sdk based projects are built using the same sdk which we commonly refer to as the .NET Core sdk. With the help you all provided, I was able to reproduce the error in Azure DevOps with the net472 WebJobs 2.0 sdk based project (if you still don't believe me, you can check the sample project here - https://github.com/vijayrkn/Repro1276/blob/master/WebJobs472Sdk/WebJobs472Sdk.csproj). The underlying error is from Microsoft.NET.Sdk which is the first line in this project and we will get the issue fixed.  

>Compared to the effort in finding the workaround you mentioned, how much effort was spent researching the changes that went into production and how to remediate or rollback those?
- Regarding the option to opt into the old behavior, I have already tagged the right team asking for the options. I was not spending time to find the work-around but to find the actual cause of the error. 

>No, not true. The easiest work-around for us is to do nothing 
- There has been a lot of work-around options posted in the top of this thread. Having looked at the repro & actual code code throwing the error, the safest work-around that I would suggest is setting this property(PublishProfileImported=true) instead of adding a profile/replacing a target as mentioned above. I am not trying to say that this is the only option but if some one were to try a work-around, this is the one I suggest.

**Comment by vnekatesharao** [comment]
WE have something like  in `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\Web\Microsoft.Web.Publishing.targets`
 <PropertyGroup Condition="'$(PublishProfileName)' !='' And '$(WebPublishProfileFile)'==''">
    <WebPublishProfileFile>$(PublishProfileRootFolder)\$(PublishProfileName).pubxml</WebPublishProfileFile>
    <WebPublishProfileFile Condition="'$(_WebProjectType)' == 'WebSite'">$(WebPublishPipelineProjectDirectory)\App_Data\PublishProfiles\$(PublishProfileName).pubxml</WebPublishProfileFile>
  </PropertyGroup>

Same is used in 

    <GetPublishingLocalizedString
       ID="PublishLocalizedString_WebPublishInvalidatePublishProfileSettings"
       Condition="'$(WebPublishProfileFile)' == '' Or !Exists($(WebPublishProfileFile))"
       ArgumentCount="2"
       Arguments="$(PublishProfile);$(**WebPublishProfileFile**)"
       LogType="Error" />

So, I override 
    <PublishProfileRootFolder>Mycustomroot folder</PublishProfileRootFolder>
    <PublishProfileName>publish profile name without pubxml</PublishProfileName>

This solved the issue for me, not sure if that is right way or not

**Comment by StingyJack** [comment]
>  I have already tagged the right team asking for the options

@vijayrkn - I do believe you are trying to help and I understand the value of this form of teamwork. It's important for those who have made the mistake or created the problem to  be made aware of it so as to learn from it and avoid any repeats. 

There has been a terrible run of surprise changes that have crippled customers productivity or put us at unnecessary high risk where the general response from the MSFT team that caused it has ranged from indifferent to unapologetic to a behavior that is best described as criminally negligent. The team you have reached out to appears to be somewhere in this negative spectrum, and that is not ok. Especially as an example to be getting set by an industry leader.

Workarounds are supposed to be temporary. They should not be getting piled up but without a proper resolution, it will be inevitable.

**Comment by anderslaub** [comment]
@vijayrkn following a number of bug reports on a msbuild script I wrote long-ago I tracked down the issue to $(PublishProfile) being set to hardcoded "FileSystem" in Microsoft.NET.Sdk.ImportPublishProfile.targets 

Then I blamed..
https://github.com/dotnet/sdk/blame/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.ImportPublishProfile.targets

And happily noticed that you already found the cause it and removed `<PublishProfile Condition="'$(PublishProfile)' ==''">FileSystem</PublishProfile>` a month ago.

Thank you for getting this fixed - it was simply this property name clash after all.

Do you know when this change in dotnet sdk will be released wide-spread (Devops VS agents, VS etc.)?

**Comment by vijayrkn** [comment]
This change should be available in the .NET Core sdk releasing with .NET Core 3.1 (Visual Studio 16.4). I have already given the change to Azure DevOps. I don't know of their exact schedule but shouldn't take that long.

**Comment by Brilbroeder** [comment]
Any confirmation yet this is solved in VS 16.4 ?

**Comment by StingyJack** [comment]
@vijayrkn - That stale bot and its ilk (docker-desktop-robot, etc) are community-destructive because it does not discern between user/contributor activity and maintainer/owner activity. Issues where people report a problem or ask for help will get auto-closed if an owner/maintainer does not take the time to respond even once. 

Ignoring any of these types of requests is unethical for anyone who is profiting from the same repo in some fashion, and is a jerk move in general. The only exceptions to this would be things that are clearly spam or are directly abusive to a person or team (criticism is not abuse, though some try to bend it that way).

Please have it removed from this repository.  If you need to tag or forward to someone else, thats fine, but I'm holding you to being the POC until then.

Besides, the correct way to close issues is by actually having someone address them. The usual argument for this kind of auto-closure is "we dont have resources to do that", which is also usually bogus because the resources were available to create the problems, and there are resources creating more problems now that could be reallocated. Microsoft used to do Bug Jails and have QA, but now its just passing along all these quality issues that create productivity problems and delays for us.

**Comment by Brilbroeder** [comment]
Although I agree with the sentiment. But your comment is totally uselless here, MS support people helping us out are by no means in the power to change that stale policy. Just use the system against itself as I did. Just ask a question and the stale is gone ;-)

**Comment by vijayrkn** [comment]
Yes, This issue is fixed in 16.4.

**Comment by StingyJack** [comment]
@Brilbroeder - if nobody points it out or complains, it will be considered acceptable and becomes policy. This is how dumb and terrible things like how MSFT must lock every post or forum thread on MSDN or Dev comm after some arbitrary age or idle time despite the usefulness to everyone of leaving it open for for additions and follow ups.

Stalebot is new-ish and I've asked to have it removed from a few Ms repos already for this same reason and manner, and it has been removed. I wouldn't care about it actually cleaning up reporter-abandoned issues, but at last check it doesn't and the maintainer didn't feel the need to update it.

**Comment by vijayrkn** [comment]
I can't speak to this repo because I am not a maintainer for this repo.

**Comment by StingyJack** [comment]
You do or do not work for Microsoft in any official capacity?

**Comment by timheuer** [comment]
FWIW, I'm not a huge fan of the stalebots as well (probably could be tuned).  @StingyJack Vijay isn't the maintainer of *this* repo so he can't do that.  I'd actually recommend adding a new issue focused just on that request and get repo owner attention as a separate issue.

**Comment by StingyJack** [comment]
@timheuer - I can only go by the "Member" tag on his name, and I would figure that a member could reach the owner more efficiently than a new issue that has to go through triage, but stalebot here (and not in the new place) was actually discussed and resolved last week on another thread so its moot anyway.
