### ISSUE TITLE
Update VS2019 images to 16.3.9

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/azure-pipelines-image-generation#1397]
There is a parallel project build issue that keeps hitting [microsoft/terminal](https://github.com/microsoft/terminal) which was [fixed in 16.3.9](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.3.9). All Centennial projects that are built on VS2019 agents will eventually run into it so long as the agents predate 16.3.9.

This request tracks updating the agents to 16.3.9.

**Comment by kaylangan** [comment]
This will be fixed in the next deployment (we pull in the latest version of VS with each deployment).

**Comment by DHowett-MSFT** [comment]
Awesome! Do you have a timeline for that deployment?
Thanks!

**Comment by DHowett-MSFT** [comment]
Is there a timeline for this deployment? Thanks.

**Comment by sven-n** [comment]
Hello,
the [newest release](https://github.com/microsoft/azure-pipelines-image-generation/releases/tag/vs2019%2F20191204.1) includes VS 2019 16.4. I’m currently waiting for a deployment on the Azure Pipelines, too.
Is there any timeline yet? Are we even asking at the correct place here? ;-)

We need it, because it contains support for .NET Core 3.1.

Thank you

**Comment by kaylangan** [comment]
16.3.9+ is almost completely rolled out to all pools. Should be out everywhere by the end of the week.

**Comment by dragnilar** [comment]
@kaylangan Isn't this resolved?

**Comment by al-cheb** [comment]
Hello, @dragnilar 
We are planning to update Visual Studio 2019 version 16.5 on our images after official release.

**Comment by maxim-lobanov** [comment]
Since initial request was about VS 16.3.9, we are closing the issue because the current version of installed VS is 16.4.5. VS 16.5 will come soon
