### ISSUE TITLE
Update CMake on Hosted Mac Agents to 3.15+

### ISSUE THREAD

**Issue by thomthom** [microsoft/azure-pipelines-image-generation#1405]
Currently the macOS agents lists their CMake versions as `3.6.4111459` which dates back to 2016. There's been considerable improvements to CMake since then. CMake 3.15 added some important features/improvements. I see that the VS2019 and VS2017 Windows agents both have 3.15.4 already.

Would be nice if there was macOS agents with matching CMake versions.

**Tool information**
- Tool name: CMake
- Add or update? Update
- Desired version: 3.15

**Areas and ecosystems**

- [ ] Android
- [x] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
macOS 10.13, macOS 10.14

**Workaround**

Dunno...

**Are you willing to submit a PR?**
If I have anything I could submit, yes.

**Comment by remyjette** [comment]
The version listed is under the Android section, and it's 3.6 because that's the default CMake version included with Android Studio. https://developer.android.com/studio/projects/add-native-code#vanilla_cmake

CMake 3.15.5 also be available on the hosted agents, somewhere in the PATH. If you're building Android you should be able to use the instructions here https://developer.android.com/studio/projects/add-native-code#use_a_custom_cmake_version to specify to use it.

**Comment by maxim-lobanov** [comment]
Hi, sorry for confusing docs. It shows Android Studio cmake instead of default one.
Actually, default `cmake` on macOS images is `3.15.5`.
```
which cmake
cmake --version
```
=>
```
/usr/local/bin/cmake
cmake version 3.15.5
```

**Comment by maxim-lobanov** [comment]
Docs were updated
