### ISSUE TITLE
Hosted Agents are returning errors for "On March 23, 2020, Azure Pipelines will remove Windows Server 2012 R2 with Visual Studio 2015(`vs2015-win2012r2`), macOS High Sierra 10.13 (`macOS-10.13`), and Windows Server Core 1803 (`win1803`) from our hosted pools."

### ISSUE THREAD

**Issue by gercheq** [microsoft/azure-pipelines-image-generation#1498]
**Describe the bug**
We're using the hosted agent on AzureDevops but we still get this error. 

**Expected behavior**
We should be able to deploy without any issues as a paying customer.

**Actual behavior**
Create a new build. Release pipeline will fail.

On March 23, 2020, Azure Pipelines will remove Windows Server 2012 R2 with Visual Studio 2015(`vs2015-win2012r2`), macOS High Sierra 10.13 (`macOS-10.13`), and Windows Server Core 1803 (`win1803`) from our hosted pools.

**Image impacted**
WINCON

**Comment by maxim-lobanov** [comment]
Hello, it is expected behavior. Per error message, Windows Container will be deprecated in a few weeks.
Per official blog post, the bunch of Brownout will happen before 23 March. During that, all builds in those pools fail.
Please see official blog post for details: https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/

**Comment by gercheq** [comment]
@maxim-lobanov

That blog post doesn not explain how to update images for hosted agents. 

As an end user, we do not have any control over the Windows Container.


![image](https://user-images.githubusercontent.com/69855/76535171-80a8cf80-648b-11ea-9262-094a93e04a96.png)


![image](https://user-images.githubusercontent.com/69855/76535213-961df980-648b-11ea-9f52-989394aa3362.png)

**Comment by maxim-lobanov** [comment]
@gercheq , As I know, there is no way to continue using Hosted Windows Container because it will be removed.
So you have to migrate your build definitions to one of the available images. Currently, the following images are available for hosted agents:
1) Windows Server 2019 with Visual Studio 2019
2) Windows Server 2016 with Visual Studio 2017
3) Ubuntu 18.04
4) Ubuntu 16.04
5) macOS X Mojave 10.14
6) macOS X Catalina 10.15

Please follow [this guide](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent) to reconfigure your build definitions.
Also please pay attention that the [environment](https://github.com/actions/virtual-environments#available-environments) of those images is different from Windows Container image. Please see [docs](https://github.com/actions/virtual-environments#available-environments) for details.

If you need to keep the same environment that you have currently on Windows Container image, [self-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops) is the single solution.

**Comment by gercheq** [comment]
We don't really care about the Hosted Windows Container. We've created a new Azure Pipeline and disabled the old Hosted Agent. You can see the second screenshot on my previous message. I'm assuming we're good going forward.
