### ISSUE TITLE
Image generation should prime the .NET fallback cache for each SDK version

### ISSUE THREAD

**Issue by vtbassmatt** [Microsoft/azure-pipelines-image-generation#224]
Per offline discussion with @AArnott and some others, the fallback cache isn't primed for all SDK versions of .NET Core. @chrisrpatterson pointed out we do this for [at least one version](https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/scripts/Installers/Install-DotnetSDK.ps1). If we factor this so that it happens for each SDK version, we can potentially save 2 minutes per build when `dotnet build` is invoked.

**Comment by AArnott** [comment]
Why did this get closed? I just saw [a build](https://andrewarnott.visualstudio.com/OSS/_build/results?buildId=66&view=logs) where I'm using one of the preinstalled SDKs instead of one I installed myself, and *still* got hit by the decompression tax. 
And even if you won't prime each SDK version, where is the issue tracking the agent setting the env variable to prevent the SDK from decompressing the whole cache so I don't pay to uncompress packages that I don't need?

**Comment by bryanmacfarlane** [comment]
Opening back up.

**Comment by bryanmacfarlane** [comment]
@lokesh755 please investigate

**Comment by dakale** [comment]
This _might_ be resolved. I didnt do the work and Lokesh is OOF but we rolled out a new VS2017 image last week that contains this updated dotnet installer: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/Install-DotnetSDK.ps1 which creates a few projects from templates for each sdk version installed
