### ISSUE TITLE
Databases: Request to add SQLExpress to hosted agents (Linux, Windows)

### ISSUE THREAD

**Issue by bveerendrakumar** [microsoft/azure-pipelines-image-generation#241]
Hi,
Lot of teams need sqlexpress on hosted agents to build variety of solutions, especially mobile apps need sql express for the build to happen. Can you please help adding SQLExpress on hosted agents? We can be in preview if it needs to be. Please reach out me vballa@microsoft.com for any details you may need.

@DavidStaheli Please help.

**Comment by Ajay-MS** [comment]
@bveerendrakumar 

I assume here you mean SQLite instead of SQL express for the hosted agents. 

As SQLite is well maintained with regular releases. By pre-installing it, SQLite version could be stale over the time. Since it is easier to install on the fly, I recommend installing SQLite version on the fly. 

**Linux hosted agent**

In your pipeline, add bash script task and add the below-mentioned script as the inline script:
```
sudo apt-get update
sudo apt-get install sqlite3 libsqlite3-dev
```

**Windows-based agent**
In your pipeline, add cmd or PS task  and add follow the script 
```
mkdir <Location to download>
cd <Location to download>
curl -O https://www.sqlite.org/2018/sqlite-dll-win64-x64-3250200.zip
```
