### ISSUE TITLE
Install Miniconda to the user's home directory

### ISSUE THREAD

**Issue by brcrista** [Microsoft/azure-pipelines-image-generation#259]
See https://github.com/Microsoft/vsts-tasks/issues/8299#issuecomment-425420608

[Installing Miniconda to /usr/share](https://github.com/Microsoft/azure-pipelines-image-generation/blob/5b0b57a464a6c50723e57b2d462c82db157d36cf/images/linux/scripts/installers/miniconda.sh#L14) caused permissions issues when we moved from Hosted Linux Preview to Hosted Ubuntu 16.04.  The `conda` executable tries to create folders and files in the /usr directory, which it now does not have access to.

By default, the Miniconda installer script will install Miniconda off of the home directory, which will fix the permissions issue.

**Comment by dakale** [comment]
We are going to fix this in the task. When the image is generated the vsts user does not exist yet so we cannot install to that users $HOME. The task can simply depend on $HOME at runtime to set the location of conda environments.

**Comment by brcrista** [comment]
I've thought about this a little more.  The `CondaEnvironment` task is designed to create and activate an environment so it can be used in downstream steps (with script).  One scenario is when you need to install more packages from other Anaconda channels, which means more calls to `conda install`.  This again tries to write the temp file where `conda` lives and needs to `sudo`.

Is there some other solution we can come up with here?  The `sudo` thing is pretty much a guaranteed build failure and something we don't want people to hit.  Could we install Miniconda somewhere and later `chmod` ownership of that directory to the user?

**Comment by stas00** [comment]
>  Installing Miniconda to /usr/share caused permissions issues when we moved from Hosted Linux Preview to Hosted Ubuntu 16.04. The conda executable tries to create folders and files in the /usr directory, which it now does not have access to.

Notice that mac has a similar problem w/ conda, yet at another path:
https://github.com/Microsoft/vsts-tasks/issues/8299#issuecomment-427971784

**Comment by andreasbotsikas** [comment]
@brcrista has an excellent point about conda and pip. In a build pipeline you may want to install packages like flake8 to do code quality assessment or even pytest to run your tests. Both packages are not needed by the application and IMHO should not be included into the conda environment. This means that during the pipeline we have to manually pip install them. This was working fine with the hosted Linux preview and now we are facing issues with the ubuntu build agent. `sudo` doesn't solve our issue because it runs in a different user and the conda environment is not activated there.

**Comment by brcrista** [comment]
@vtbassmatt reopening so we can take another look at this

**Comment by dakale** [comment]
Ive been playing around with conda on a test machine with the same image running in hosted. My understanding is that the main issue is when you are a non-root user and want to run any command that modifies the root environment, you get a permission error because the root environment in `/usr/share/miniconda` is read-only.

In my experiments it seems like I am able to eg install packages by simply passing an environment that is relative to my user account: 

```
dakale@Ubuntu1604:~/conda_test$ conda create -n MyEnv
dakale@Ubuntu1604:~/conda_test$ cat ~/.conda/environments.txt 
/home/dakale/.conda/envs/MyEnv
dakale@Ubuntu1604:~/conda_test$ conda install -n MyEnv -y numpy
```

Activating this environment makes the subsequent commands relative to this environment, which should cause it to write to ~/.conda/envs/MyEnv instead of /usr/share/miniconda. Is that not what the task currently does? Im not sure where the error/need to use sudo is being introduced

ie, on my box:
```
dakale@Ubuntu1604:~/conda_test$ conda activate MyEnv
(MyEnv) dakale@Ubuntu1604:~/conda_test2$ conda install scipy
```
works fine. Then we can see that:
```
(MyEnv) dakale@Ubuntu1604:~/conda_test2$ conda info

     active environment : MyEnv
    active env location : /home/dakale/.conda/envs/MyEnv
            shell level : 2
       user config file : /home/dakale/.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : /usr/share/miniconda  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /usr/share/miniconda/pkgs
                          /home/dakale/.conda/pkgs
       envs directories : /home/dakale/.conda/envs
                          /usr/share/miniconda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/4.15.0-1023-azure ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
with the MyEnv environment activated, the base is still the read-only environment, but everything else seems fine, with my package caches and envs directories pointing to the correct locations with what appears to be a global fallback (I am thinking we can benefit from preinstalling some common packages in a read-only fashion to this root environment during image generation)

It seems that the task can easily operate in an environment with a read-only root, in fact, there is a tiny bit of documentation around what I think is the same scenario: https://conda.io/docs/user-guide/configuration/admin-multi-user-install.html , so I believe this should be well supported. 

Any thoughts @brcrista or @vtbassmatt ? I cant come up with any scenario where the base image needs to change, so maybe we can move this discussion back to the task. 

Other notes: https://conda.io/docs/user-guide/troubleshooting.html#permission-denied-errors-after-using-sudo-conda-command

Recommends _never_ doing sudo conda so thats two places where the information available points to multi-user configurations with a read-only root being common and viable

**Comment by brcrista** [comment]
It's true that an environment created in a user directory should work fine.  I made a change to the task this sprint to do this: Microsoft/azure-pipelines-tasks#8800.

However, this still won't work for the base environment (when you install things globally) and for updating conda.  On a hosted agent, there's usually not much reason to create an environment, and you can just install things to the base environment.

+1 for "never sudo;" we had a customer hit this issue (see above).

**Comment by brcrista** [comment]
We might be able to fix by installing in `/opt` instead of in `/usr`

**Comment by dakale** [comment]
opt has the same permissions as usr, the only location that would not be owned by root is the user directory at /home/vsts that does not get created until after the image generation process. 

Ill need to take a deeper look at the changes to the task you linked above, but I believe its a good change for now. I agree that having the global environment be read only doesnt add much benefit to hosted, because its going to get wiped out after the build anyway. I think the task is the right place to continue to make these changes though because it decouples the image generation process from needing to know about what user accounts get created after the fact

**Comment by brcrista** [comment]
We shipped a fix in the provisioner for this on Hosted Ubuntu 16.04.  I validated on build canary that we no longer need to `chown` the installation directory to update Conda.

I'll update https://docs.microsoft.com/azure/devops/pipelines/languages/anaconda accordingly.
