### ISSUE TITLE
JavaScript and Node.js: Add Node.js 10.13.0 LTS as the default version of Node.js (Linux, Windows)

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#405]
JavaScript and Node.js: Add Node.js 10.13.0 LTS as the default version of Node.js (Linux, macOS, Windows)

**Comment by Astrophizz** [comment]
Despite this targeting January, Node.js was updated to 10.13.0 on the Hosted VS2017 image in production either late on December 10 or early December 11. This isn't documented anywhere but I noticed when a build started to fail due to an npm package being incompatible with Node.js 10 😰 Fortunately the minor version update to fix it wasn't problematic.
