### ISSUE TITLE
C/C++: Add ccache 3.2.4 (Linux)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#435]
C/C++: Add ccache 3.2.4 (Linux)

**Comment by willsmythe** [comment]
Installing ccache (`sudo apt-get install ccache`) takes about 45 seconds on the hosted Linux agent today. Pre-installing would avoid this. As it stands now, smaller projects don't see much (if any) improvement to build time, and actually see longer build times in cases where there isn't a cache hit.

**Comment by willsmythe** [comment]
ccache should also be added to the hosted macos image (`brew install ccache`)

**Comment by davidstaheli** [comment]
@kaylangan, I'm told this is necessary for caching in pipelines (for macOS too).

**Comment by willsmythe** [comment]
Like we do for [Conda](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/anaconda?view=azure-devops&tabs=ubuntu-16-04#add-conda-to-your-system-path), we should set an environment variable in the image (e.g. `CCACHE`) that points to the path where ccache was installed. This will make it easier for users to add it to their $PATH (which most users will want to do since this path contains ccache aliases for `gcc`).

We could then just need to document a step:

```yaml
- bash: echo "##vso[task.prependpath]$CONDA"
  displayName: Add ccache to PATH
```

This solution is also nice because it will work consistently for users in both the Linux and macOS images.

**Comment by willsmythe** [comment]
In my example above, I was assuming `$CCACHE` was not necessarily the install path of `ccache`, but was `/usr/lib/ccache` (the default on Ubuntu) which is where `gcc` and other links (which point to `ccache`) reside. 

If we think users might be confused by what this variable points to. maybe `$CCACHE_LIB` (or something like this) would be a better name ...
