### ISSUE TITLE
Common tools: Add/update to OpenSSL 1.1.0j (32-bit) (C:\OpenSSL-v11-Win32\bin) (or latest) (Windows)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#458]
Common tools: Add/update to OpenSSL 1.1.0i (32-bit) (C:\OpenSSL-v11-Win32\bin) (or latest) (Windows)

**Comment by redboltz** [comment]
I'm new to azure pipelines. I'd like to use openssl from my C++ programs.

Before I found this issue, I tried to find OpenSSL header files and I noticed that only binary files are provided currently:
https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md#openssl

I tried to build openssl by myself from github. But build failed due to `nasm` not found. I think that everyone who want to use openssl doing `git clone` is inefficient.

So, I expects adding OpenSSL not only binary but also for developer files e.g. header, library, and so on.

**Comment by redboltz** [comment]
> I tried to build openssl by myself from github. But build failed due to nasm not found.

Now I build openssl as follows:

https://github.com/Azure/azure-storage-cpplite?fbclid=IwAR1JIbN_M7zLUQIYjifNasywAYbc0W7VG6rwmqnx_XhZxWWs66qyNK-wwd0#prepare-and-build-the-dependencies
