### ISSUE TITLE
JavaScript and Node.js: Add Node.js 10.13.0 LTS as the default version of Node.js (macOS)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#576]
JavaScript and Node.js: Add Node.js 10.13.0 LTS as the default version of Node.js (macOS)

**Comment by calebcartwright** [comment]
The [default version of Node.js on macOS is still 6.x](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#language-and-runtime), but [Node 6.x has been EOL since April 30](https://github.com/nodejs/Release#end-of-life-releases)

I know we can use the Node Tool Installer task to work around this. However, the default version of Node on Ubuntu and Windows images is 10.x so it would be great to get a non-EOL version as the default on Mac agents as well.
