### ISSUE TITLE
Installing msys2 via choco freezes in Windows Server 2019

### ISSUE THREAD

**Issue by letmaik** [microsoft/azure-pipelines-image-generation#742]
**Describe the bug**
Installing MSYS2 via chocolatey freezes at the very end and never finishes. The same works fine in the vs2017-win2016 image.

**Expected behavior**
Should not freeze.

**Actual behavior**
A description with steps to reproduce the issue.

1. `- script: choco install msys2 --params "/InstallDir:c:\msys64"`
2. Run CI and observe that the install freezes.

**Image impacted**
windows-2019

**Comment by gekeugen** [comment]
The freezing can occur due to the fact that the `ridk` cannot install a system update on Windows Server 2019 at the end of the installation. You can use the `"/ No Update"` key to not install a system update.

Then the command will be as follows:
`choco install msys2 --params "/NoUpdate /InstallDir:c:\msys64"`

**Comment by letmaik** [comment]
@gekeugen Why do you mention `ridk` here? There's no ruby involved when installing msys2. You probably meant that msys2 cannot install the system update. So the question is: why not? It works in the win2016 image.

**Comment by gekeugen** [comment]
My mistake, ridk here does not matter. An update is put through packman.
The msys2 installer is here https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/msys2/tools/chocolateyinstall.ps1
