### ISSUE TITLE
Support existing VNET with NSG on building images

### ISSUE THREAD

**Issue by tehho** [Microsoft/azure-pipelines-image-generation#764]
**Describe the bug**
We are getting logging tries from brazil on our vms in west europe when building this without an nsg.

**Expected behavior**
Since we don't have the option to add an vnet to this resource this is expected

**Wanted behavior**
Added options in the builder to support mounting the vm in an existing vnet and subnet with a preconfigured nsg to mitigate these logging tries

1. Step 1
Add following json to builders:
            "virtual_network_name": "{{user `vnet_name`}}",
            "virtual_network_resource_group_name": "{{user `vnet_group_name`}}",
            "virtual_network_subnet_name": "{{user `subnet_name`}}"

2. Step 2
Add following json to variables:
  "vnet_name": "ARM_VNET_NAME",
  "vnet_group_name": "ARM_VNET_GROUP_NAME",
  "subnet_name": "ARM_SUBNET_NAME"

**Image impacted**
windows 2015,2017,2019,Container
Linux

**Comment by joebourneMS** [comment]
Hello, If I am understanding correctly, I believe you are using these image scripts to generate your own images and running your VMs? If I understand that correctly, the changes you're proposing aren't something we would add to this repo because this repo is where we build our Azure DevOps productions images from.

I would advise you to fork this repo, and then add the specific changes you want there if that works? Let me know if you have additional questions.
