### ISSUE TITLE
Create and Publish AWS AMI (Amazon EBS volume) for Pipeline Images

### ISSUE THREAD

**Issue by rorychatterton** [microsoft/azure-pipelines-image-generation#771]
A number of our Clients leverage Azure DevOps with services hosted within AWS. 

Today it is challenging to keep self-hosted packer images up to date with the Microsoft Repository, however keeping parity between the two is a goal.

It would be fantastic if Microsoft could create AWS Packer Images for each of the build pipeline images, and Publish them as AMIs onto the AMI Marketplace.  By providing these AMIs as a Service, published at the same time as the Hosted Images, the on-boarding experience to Azure DevOps for AWS would be significantly improved.  

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [X] Other

**Image impacted**
- [X] Ubuntu
- [X] Windows

(Sorry - I don't have enough access to add Labels).

**Comment by joebourneMS** [comment]
Thanks for the feedback, Rory. This is an interesting scenario. Do I understand this correctly, your clients are generating our image and hosting them on AWS VMs?

If so, this is not something we're likely to get to any time soon unfortunately. I will put it on our team's internal backlog, but please set your clients expectations appropriately that this is very low on our list for now.

**Comment by rorychatterton** [comment]
Thanks for the feedback!

That is correct. 

Today, we take your existing Packer Images, update them to use the AWS EBS builder, make a few modifications to the initialization scripts and run them. If they were published pre-baked, we could simply deploy the base image and drop on our Agent + Configuration.

Thinking out loud - It would be worth doing something similar in the Azure Marketplace by making the images available for people to use in their VNETs, or even those hosting their own VSTS services in Azure. 

All good re: Clients.

**Comment by ryanspletzer** [comment]
At my company we use both AWS and Azure and are using Azure DevOps to deploy to both. Our build VMs run in AWS, though. We are referencing this repo as a git submodule to re-use all the scripts and steps in the packer template that are generously provided and maintained, and we simply swap out the Azure image builder for a parameterized AWS AMI builder in our own packer template. (We add a couple built-in pauses / reboots in the process to accommodate specific peculiarities that arise in AWS land from their upstream vanilla AMI. On the whole it works great, though.)

In a previous life I used to have to maintain static build VM's, but because of this repo we can have ephemeral build infrastructure. It's great!

**Comment by andyflatt** [comment]
@ryanspletzer 

Hi Ryan,

I am just about to do the exact same thing as you have done.  Is there any chance you can share some details on what you needed to change to get this to work?
