### ISSUE TITLE
Update mvn to 3.6.0 

### ISSUE THREAD

**Issue by aasim** [Microsoft/azure-pipelines-image-generation#799]
**Tool infomation**
- Tool name: mvn
- Add or update? update
- Desired version: 3.6.0
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [x] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Add the appropriate label for the image or images that should be updated (e.g., mac, ubuntu, window).

mac, ubuntu, windows

**Comment by DavidStaheli** [comment]
@aasim thank you for reporting this.  The recently released macOS, Linux, and Windows images now include Maven 3.6.0.  Is there any chance this problem was encountered 1+ months ago before we provided 3.6.0?  I'll close this for now, but please comment/reopen if there could still be an issue.  Thanks again.
