### ISSUE TITLE
Please Add Microsoft.VisualStudio.Component.Windows10SDK.16299 to Server 2019 VS 2019 image

### ISSUE THREAD

**Issue by csdhome** [microsoft/azure-pipelines-image-generation#860]
- Visual Studio Component ID: Microsoft.VisualStudio.Component.Windows10SDK.16299
- Tool name: Windows 10 SDK for RS 3 version 16299
- Add or update? Add
- Desired version: 16299
- If this is an add request:
  - Brief description of tool: The Windows 10 SDK for RS 3 for Visual Studio 2019
  - URL for tool's homepage: https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2019#desktop-development-with-c

**Areas and ecosystems**
- [ ] Android
- [x] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [x] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [x] Other
- [x] UWP Development

**Image impacted**
windows-2019
Windows Server 2019 with Visual Studio 2019

**Comment by BrianMouncer** [comment]
We recently started building UWP ARM64 versions of our code base.
I want to also build our windows desktop C++ code for ARM64, but the needed win 10 SDK and build tools for ARM64 seem to be missing from the hosted vs 2017 agent.

When you add Windows 10 SDK 16299, please install "all of it" so that we can build both uwp AND desktop C++ projects.  If you can not add all of it, then at least add the following ARM/ARM64 parts...


Microsoft.VisualStudio.Component.Windows10SDK.16299.Desktop.arm | Windows 10 SDK (10.0.16299.0) for Desktop C++ [ARM and ARM64]
Microsoft.VisualStudio.Component.VC.Tools.ARM | Visual C++ compilers and libraries for ARM | 15.8.27825.0 | Optional
Microsoft.VisualStudio.Component.VC.Tools.ARM64 | Visual C++ compilers and libraries for ARM64 | 15.9.28230.55 | Optional
Microsoft.VisualStudio.Component.UWP.VC.ARM64 | C++ Universal Windows Platform tools for ARM64 | 15.0.28125.51 | Optional


Thanks

**Comment by kaylangan** [comment]
Fixed in #770. Will roll out in M152 release.
