### ISSUE TITLE
Update/Add vcpkg to Hosted Windows 2019 with VS2019 image

### ISSUE THREAD

**Issue by vSzemkel** [Microsoft/azure-pipelines-image-generation#884]
There is no vcpkg package manager installed in Hosted Windows 2019 with VS2019 image. 
There is one in VS2017 image, however.

**Comment by jwillemsen** [comment]
See #749

**Comment by kaylangan** [comment]
We roll out updates every 3 weeks so this will be available soon if it's not already.

**Comment by OmerRaviv** [comment]
@kaylangan Thank you! It's been 1 month since #749 was merged to master, but as far as I can see it's still not updated on the VS2019 image (I checked the Details tab for the "Azure Pipelines Hosted Windows 2019 with VS2019 image" and it's not mentioned anywhere). Any idea what's happening there? 

Also, related bit of feedback: it would be really helpful if the Details tab would include the date the image was last updated (or a link back to the specific commit on this GitHub repo).

**Comment by kaylangan** [comment]
@OmerRaviv We've had delays deploying our M151 release ([see releases here](https://github.com/microsoft/azure-pipelines-image-generation/releases)). You can see what's in the M151 payload in the `releases/VS2019/151.5` branch. It'll have vcpkg when it finally deploys. Apologies for the delays.
