### ISSUE TITLE
Request: Upgrade npm to 5.7.1 (latest release) to support npm ci

### ISSUE THREAD

**Issue by edqwerty1** [Microsoft/azure-pipelines-image-generation#89]
This request is for the VSTS Hosted VS2017 image

Currently 5.5.1 is installed, request this gets upgraded to 5.7.1

Reason explained in this blog post http://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable

I have already switched my builds over to using the YARN tool installer/task.  Even on a small project with a few gulp build tasks npm was regularly taking upwards of 5 minutes to work.  Yarn brought this down to ~1.30.  But now we have a situation where the build server is using different tooling from development.

Hopefully npm ci will offer even more improvements in build times.

**Comment by lokesh755** [comment]
The latest image which is getting rolled out has npm 5.6.0 installed. Will make sure to update npm in next release of image (probably with in 1-2 weeks).

**Comment by bryanmacfarlane** [comment]
There's a tool installer task that will pull node and npm at build time.  That's better than waiting and sliding on what happens to be on the image.

**Comment by juliank** [comment]
Could you please elaborate on the tool installer task @bryanmacfarlane ? I have found and added the "Node Tool Installer" task, which enables us to specify the version spec as 8.x, to (currently) get Node 8.10.0. But the npm version is still only 5.6.0. And it is the npm version we need to get to 5.7.1 to utilize npm ci to speed up our builds.

**Comment by bryanmacfarlane** [comment]
@juliank - have you tried specifying 8.11.2 explicitly?  You can also try to check the box, check for latest on the task.

@lokesh755 - I think this means the tools cache on the image needs to be updated

I think 8.x is matching 8.10.0

**Comment by juliank** [comment]
Thank you for the quick response @bryanmacfarlane . Ticking the "Check for latest" on the task resulted in node version 8.11.2. The npm version however, remains at 5.6.0, as can be seen from the build log:
```
2018-06-02T11:45:48.8416863Z [command]C:\Windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\node\8.11.2\x64\npm.cmd --version"
2018-06-02T11:45:49.9700482Z 5.6.0
```

**Comment by bryanmacfarlane** [comment]
hmmm - I guess latest node LTS doesn't include 5.7.1.  Will look into it

**Comment by lokesh755** [comment]
@juliank Unfortunately we could only install node LTS versions which does not have npm (>5.6.0). You can still use node installer task to install any node version. For example you can install 10.3.0 node version which has npm 6.1.0 which has npm ci. I hope it's useful.

**Comment by lokesh755** [comment]
@juliank  Does it resolve your issue ?

**Comment by juliank** [comment]
Thank you @lokesh755 , using Node 10.x gave us npm 6.1.0 and enabled us to use `npm ci` instead of `npm install`.

Using `npm ci` didn't however improve the build speed as much as we had hoped for (2x-10x faster, according to [the release notes](https://github.com/npm/npm/releases/tag/v5.7.0)). Using npm 5.6.0 `npm install` took 144 seconds, while with npm 6.1.0 `npm ci` took 111 seconds. But that's a completely different issue, and not your problem :-)

**Comment by juliank** [comment]
Thank you for the tip @bryanmacfarlane. By using `npm install npm@latest -g` we were able to set the node installer task back to 8.x, and still get npm 6.1.0 and the ability to use `npm ci`.

Using `npm ci` (with npm 6.1.0) took 2.9 minutes, compared to 5.2 minutes with `npm install` (with npm 5.6.0). So we're at least getting close to the 2x speed increase [promised by the npm 5.7.0 version](https://github.com/npm/npm/releases/tag/v5.7.0) (although `npm install` with npm 6.1.0 took only 3.5 minutes, so the increase isn't that good after all...). However, adding the `npm install npm@latest -g` step added a stunning 4.6 minutes to the build process, so it is not at all worth it.

And since you bring up Node 10 and LTS: From [what I can read](https://github.com/nodejs/Release#lts-schedule1) 10.x will enter LTS later this year in October (lasting until April 2020). So from my point of view, I can't see that as a reason to not adopt it. Or is there a chance that Node 10 _won't_ go into LTS mode for some reason?

**Comment by bryanmacfarlane** [comment]
yeah, when it gets to LTS it will be on the pool.  I'll look into whether we can get 5.7 on the image until then and keep the issue open ...  As long as they consider it released/LTS (odd why it doesn't just come with node 8) then we don't have an issue.  Our image gen would eat the 5 minutes.

**Comment by ahoy84** [comment]
it would be nice to have the npm updated because its chewing most of our build time to update npm to > 5.7.0 version. updating npm takes like 3-5 mins!!!

its like a lifetime for the build to finish considering having other build task (i.e 11 build tasks).

**Comment by lokesh755** [comment]
Please refer my previous comment.. https://github.com/Microsoft/vsts-image-generation/issues/89#issuecomment-394087637

**Comment by ArgTang** [comment]
@lokesh755 node have released a new LTS (8.12.0), wich includes npm version that supports ci. Can this be revisited?

**Comment by lokesh755** [comment]
We've generated new image, which has Node LTS 8.12.0. We will update all the regions with latest image within a week

**Comment by taspeotis** [comment]
Hi, I'm in the Australia region and "npm ci" fails as the npm version is too old (5.6). Is the rollout still in progress, or should I be using something like the node tool installer to install 8.12?

**Comment by bryanmacfarlane** [comment]
until then, pulling JIT via tool installer is an option

**Comment by taspeotis** [comment]
Okay so just today:

```
user-agent = "npm/6.4.1 node/v8.12.0 win32 x64"
```

Thanks everyone for contributing to this issue.

**Comment by coffeymatt** [comment]
Npm ci is working for me now, thanks for this! Might be worth adding to the npm command drop down in vsts to encourage people to use it.

**Comment by edqwerty1** [comment]
UK/West Europe Hosted 2017 agent still showing user-agent = "npm/5.6.0 node/v8.11.4 win32 x64", I think switching to an Aussie build agent for faster builds might not workout so well.. I will keep checking!

**Comment by edqwerty1** [comment]
West Europe user-agent = "npm/6.4.1 node/v8.12.0 win32 x64"

Since raising this ticket npm install times have steadily come down from 5 minutes to 1:40-2:00 so a combination of better Azure network and NPM improving the speed of install has helped a lot already.

From my incredibly brief testing:
npm install           - 1:50
npm ci                  - 1:10
Use Yarn + Install - 1:35

Looks like a good win! As @coffeymatt  says, might be worth adding this to the npm tasks docs at least.

**Comment by DavidStaheli** [comment]
FYI @alexmullans about this suggestion for the npm task docs.
