### ISSUE TITLE
.Net 48 not found

### ISSUE THREAD

**Issue by riezebosch** [microsoft/azure-pipelines-image-generation#973]
[8.txt](https://github.com/microsoft/azure-pipelines-image-generation/files/3222289/8.txt)
```
==> vhd: Provisioning with powershell script: C:\agent1\_work\533\s\images\win/scripts/Installers/Install-NET48.ps1
    vhd: Downloading NDP48-DevPack-ENU.exe...
    vhd: Starting Install NDP48-DevPack-ENU.exe...
    vhd: Non zero exit code returned by the installation process : -1073741819.
    vhd: -1073741819
```

```
==> vhd: Restarting Machine
==> vhd: Waiting for machine to restart...
    vhd: A system shutdown is in progress.(1115)
    vhd: #< CLIXML
    vhd: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
    vhd: pkrvmibal7ceu6l restarted.
==> vhd: Machine successfully restarted, moving on
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\agent1\_work\533\s\images\win/scripts/Installers/Vs2017/Validate-SSDT.ps1
    vhd: SSDT version 15.1.61903.1040 installed
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\agent1\_work\533\s\images\win/scripts/Installers/Vs2017/Validate-Wix.ps1
    vhd: Wix Toolset version  installed
    vhd: Wix Extension version 0.9.21.62588 installed
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\agent1\_work\533\s\images\win/scripts/Installers/Validate-NET48.ps1
    vhd: .Net 48 not found
```

**Comment by majorvin** [comment]
Any updates on this one? I can still reproduce the problem on the latest master a373311832e031acdbe66d0472f41f5dfb7d10d9

**Comment by yannduran** [comment]
It's 2019-06-16 and I **still** can't run pipelines for projects using .NET 4.8! I can't believe it's taking/taken this long to install a .NET SDK, for a framework that's supposed to be a **side-by-side installation**. It should simply have been installed on the image **with VS 2019**, like it is on our own machines.

I get that milestones are sometimes delayed, but that's what **hotfixes** are for! This is holding up people **around the world**!!!

Someone should be held accountable for this, because they essentially **broke** _Azure DevOps Pipelines_ for customers using the latest version of Visual Studio and the latest version of the .NET Framework. 

Don't Microsoft devs **use** Azure Pipelines??? This should have been picked up **internally** and FIXED over a month ago.

**Comment by boekabart** [comment]
Same issue trying to build C# 8 on dotnet core - latest SDK in the image is still 2.2.105. Isn't this a matter of re-running the generation script for this image, guys???

**Comment by kaylangan** [comment]
.NET 4.8 should now be available on all accounts. Please let me know if you're still not seeing it.

**Comment by riezebosch** [comment]
```
==> vhd: Provisioning with powershell script: C:\agent1\_work\913\s\images\win/scripts/Installers/Validate-NET48.ps1
    vhd: .Net 48 not found
```

I don't know what you mean by 'all organizations' but it is still failing on me and I don't see any changes in scripts that could've fixed it anyway.

**Comment by majorvin** [comment]
I just pull the latest release `VS2017/20191009.1` and still getting the same error.
