### ISSUE TITLE
Powershell task does not work correctly for piped inputs in VS2017 hosted agent (works fine on ubuntu)

### ISSUE THREAD

**Issue by atbagga** [microsoft/azure-pipelines-image-generation#975]
**Describe the bug**
Powershell task does not work correctly for piped inputs in VS2017 hosted agent (works fine on ubuntu)

**Expected behavior**
Task behaviour should be same on both vs2017/2019 hosted agent and Ubuntu agent when using a powershell task

**Actual behavior**

- Server - Azure Pipelines 
    Build definition: 
https://dev.azure.com/baggaatul24/PowershellTaskIssue/_build?definitionId=160 
and 
https://dev.azure.com/baggaatul24/PowershellTaskIssue/_build?definitionId=161

- Agent - Hosted 

## Issue Description

[On a hosted VS2017 ](https://dev.azure.com/baggaatul24/PowershellTaskIssue/_build/results?buildId=955) agent something like this ```echo 'test token' | python myecho.py```
echoes some unprintable character at the start of the string. 
![image](https://user-images.githubusercontent.com/11888714/58245846-59a1d580-7d73-11e9-8022-dabdd9412378.png)

Same script works [fine on ubuntu ](https://dev.azure.com/baggaatul24/PowershellTaskIssue/_build/results?buildId=956)with powershell task.

This should be easily reproducible given my setup. I have made the project public for your easy access. Please let me know if you need any more information from my side. 

myecho.py referred in this issue contains this code-

```
import sys
token = sys.stdin.readline()
print("Token is " + token)
```

**Comment by vtbassmatt** [comment]
Looks like more BOM shenanigans. @damccorm will https://github.com/microsoft/azure-pipelines-agent/pull/2197 fix this?

**Comment by damccorm** [comment]
Interestingly, this seems to not be an issue when using node instead of python. https://dev.azure.com/damccorm-repros/encoding-issue-repro/_build/results?buildId=82&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9

**Comment by atbagga** [comment]
Is it same as setting the environment variable as below in the powershell task? Is yes, then that did not help. I still see the same character in logs.
![image](https://user-images.githubusercontent.com/11888714/58575483-c8919980-825f-11e9-94d9-a191c6bddaaf.png)

**Comment by damccorm** [comment]
Did some research, it looks like there's a whole [host of issues](https://stackoverflow.com/questions/5419/python-unicode-and-the-windows-console/) surrounding python and powershell/the windows console. From [here](https://bugs.python.org/issue1602) it looks like it might actually be a Python bug - regardless Windows and Python clearly don't play well when the code page is 65001 (UTF-8). There also doesn't seem to be a clear workaround as best I can tell (though I admit I haven't done a deep dive on that thread).

We set the code page to 65001 so that we can render UTF-8 characters correctly in logs - setting `agent.retainDefaultEncoding` simply turns that behavior off - so that pretty clearly seems to be the issue. I'm not sure there's a workaround to fix this on our end, so I think the best path forward is probably to do one of the following:

1) Set the code page back to 437 (Windows Default) for this script. You can do this by calling `chcp 437` at the start of your script. This could lead to some of your characters not rendering correctly in the console, but otherwise is pretty safe (and most likely you won't see that impact). It will also only affect that task (vs `agent.retainDefaultEncoding` which changes the code page back to 437 for the entire job)
2) Don't pipe input in. Obviously this isn't a fantastic workaround, but it seems like if the input is passed in as parameters you won't run into this issue (though I'm not certain that one of the other issues won't bite you).

Obviously neither workaround is ideal, not sure there's much we can do on our side about this one though.

**Comment by damccorm** [comment]
Note that you can repro this issue on a windows box by running the following from powershell:

```
chcp 65001
powershell
echo 'abc' | python .\myecho.py
```

**Comment by atbagga** [comment]
Thanks for posting the detailed analysis.

Don't pipe input is not always an option because credentials should not be accepted as input params, they should be asked for via stdin. 

And when on a third party tool login doesn't work it is highly doubtful someone will be able to figure out what is going wrong in the login flow, it will not be as easy to debug as printing the input and figuring out the token is being corrupted by the python-powershell handover.

**Comment by damccorm** [comment]
That makes sense - I agree that as it stands this isn't ideal.

With that said, I'm just not sure there's anything we can do. As best I can tell, nobody has figured out a workaround for this issue while keeping the code page 65001, and there definitely don't seem to be any workarounds from the PowerShell or environment side. This seems to pretty clearly be a bug with either PowerShell or Python (or both/just how they interact), and we don't have direct control over either.

So that basically leaves 2 options: stop changing the code page to 65001 or no-op. Not changing the code page is probably not an option at this point - that opens us up to a whole other host of issues which unfortunately outweigh this one (mostly in the JavaScript world, but also elsewhere). So unfortunately that means this is probably a no-op 😕

Again, I recognize that this isn't ideal, but unfortunately this behavior is just out of our control I think.

**Comment by vtbassmatt** [comment]
Thanks for the investigation, Danny. I agree that there's not much we can do here. Python users (of which I am one 😁) can use Cmd or Bash instead of PowerShell if they need to pipe inputs like this.

**Comment by atbagga** [comment]
Thanks @damccorm! for the detailed investigation and sharing the workaround too.
