### ISSUE TITLE
Hosted Ubuntu 16.04 has some old python packages pre-installed

### ISSUE THREAD

**Issue by blackchoey** [microsoft/azure-pipelines-image-generation#978]
We have received customer report about Azure Pipeline task failures. After investigation, we found that the Hosted Ubuntu 16.04 agent assigned to customer has some old python packages pre-installed. In our case, the `cryptography 1.2.3` was installed, which released on March 2016 and doesn't meet minimum requirement for many packages. Due to the nature of pip, the old package won't be upgraded if it's referenced indirectly. Then errors will occur.
The old packages don't exist in previous hosted ubuntu 16.04 agent for the customer and my personal Azure DevOps organization also didn't been assigned agent with old package installed now. Is there a recent change that installed the old package to hosted agent? Could you help fix this if it's not the expected behavior or share reasons behind this if it's installed on purpose?

**Comment by kaylangan** [comment]
What version(s) of Python are you seeing this on?

**Comment by blackchoey** [comment]
We didn’t specify python version. We executed following command using Azure Pipelines Task Lib in our task: “sudo pip install iotedgedev==1.1.0”
According to the logs, the cryptography package exists at “/usr/lib/python2.7/dist-packages”. So the version of python should be 2.7.

**Comment by brcrista** [comment]
We did update the Python versions under `Agent.ToolsDirectory` in the latest rollout, but this is system Python.  I can't identify what would have installed this package globally.

What package are you trying to install that depends on cryptography (assuming it's public)?  What are you doing for the workaround?

**Comment by blackchoey** [comment]
Sorry for the delayed response. We installed `iotedgedev` to build solutions and some of its dependencies depends on cryptography. Since pip couldn't resolve the version of dependencies very well, it thinks the existing `cryptography 1.2.3` meets the requirement which actually doesn't meet.
As a workaround, we manually upgrades cryptography to latest version in the Azure Pipeline task to avoid errors.

**Comment by brcrista** [comment]
Thanks @blackchoey.  I wouldn't consider this a bug on the image generation side -- we don't make any guarantees that these packages won't be installed by default for system Python, and these are subject to change in the future.  It seems like you have found the right fix based on what Pip is doing.

I would recommend isolating your task from the system environment in some way.  This is good practice because if someone runs your task on a self-hosted agent, it will be installing packages globally on their agent.  You could use a virtualenv if that's an option for you and install the exact versions of packages you expect from a requirements.txt.  You also have the option to distribute your own binary files with the task.
